name: send_txt

on:
  schedule:
    - cron: "* * * * *" # This runs the script every 2 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x" # Specify the Python version you need

     run: python print('hello')