# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Send daily quote

on:
  workflow_dispatch: # Put here so you can manulaly trigger the workflow!!
  schedule:
   - cron: "0 8 * * *" # runs every day at 8am EST
   
jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install requirements
      run: python -m pip install -r requirements.txt
        
    - name: Run script
      env:
            USER1: ${{ secrets.USER1 }}
            USER2: ${{ secrets.USER2 }}
            SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
            SMTPD_PORT: ${{ secrets.SMTPD_PORT }}
            SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
            SENDER_PASS: ${{ secrets.SENDER_PASS }}
      run: python text_script.py
        
